version: "3.9"

services:
  django:
    build: ./backend
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis
      - hub
  db:
    image: postgres
    container_name: pgdb
    env_file:
      - .env.db
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pg_admin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
  redis:
    image: "redis:alpine"
    expose:
      - 6379
    ports:
      - "6379:6379"
  celery:
    build: ./backend
    command: celery -A core worker -c 3 --loglevel=INFO
    volumes:
      - ./backend:/usr/src/app/
    env_file:
      - .env.dev
    depends_on:
      - django
      - redis
  celery-beat:
    build: ./backend
    container_name: celery-beat
    command: celery -A core beat -l info
    volumes:
      - ./backend:/usr/src/app/
    links:
      - hub
    env_file:
      - .env.dev
    depends_on:
      - django
      - redis
  flower:
    image: mher/flower
    container_name: flower
    command: [ "celery", "--broker=redis://redis:6379/0", "flower", "--port=8888" ]
    ports:
      - "8888:8888"
    depends_on:
      - redis
      - celery
  hub:
    image: selenium/hub:4.1.3
    container_name: hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:4.1.3
    container_name: chrome
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=10
volumes:
  pg_data:
  pg_admin: