version: "3.9"

services:
  django:
    build: ./backend
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis
  db:
    image: postgres
    container_name: pgdb
    env_file:
      - .env.db
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pg_admin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
  redis:
    image: "redis:alpine"
    expose:
      - 6379
    ports:
      - "6379:6379"
  celery:
    build: ./backend
    command: celery -A core worker -c 2 --loglevel=INFO
    volumes:
      - ./backend:/usr/src/app/
    env_file:
      - .env.dev
    depends_on:
      - django
      - redis
  flower:
    image: mher/flower
    container_name: flower
    command: [ "celery", "--broker=redis://redis:6379/0", "flower", "--port=8888" ]
    ports:
      - "8888:8888"
    depends_on:
      - redis
      - celery
volumes:
  pg_data:
  pg_admin: